# Generated by Django 5.1.7 on 2025-03-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
