# Generated by Django 5.1.7 on 2025-03-12 13:18

import Usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[
                ("objects", Usuarios.models.CustomUserManager()),
            ],
        ),
    ]
