# Generated by Django 5.1.7 on 2025-03-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Usuarios", "0002_alter_usuario_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="telefono",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
