# Generated by Django 5.1.7 on 2025-03-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
    ]
