# Generated by Django 5.1.7 on 2025-03-18 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventario", "0004_movimientostock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                ("id_pedido", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_proceso", "En proceso"),
                            ("finalizada", "Finalizada"),
                        ],
                        default="en_proceso",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventario_detalle_pedido",
                        to="Inventario.producto",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inventario.pedido",
                    ),
                ),
            ],
        ),
    ]
