# Generated by Django 5.1.7 on 2025-03-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventario", "0005_pedido_detallepedido"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
