# Generated by Django 5.1.7 on 2025-03-21 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Contabilidad", "0001_initial"),
        ("Inventario", "0008_alter_pedido_cliente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="entradas",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="presupuesto_total",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="salidas",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="user",
        ),
        migrations.AddField(
            model_name="budget",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Transaccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ingreso", "Ingreso"), ("egreso", "Egreso")],
                        max_length=10,
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Contabilidad.budget",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Inventario.pedido",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Movimiento",
        ),
    ]
