# Generated by Django 5.1.7 on 2025-03-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Contabilidad", "0003_budget_monto_inicial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="monto_inicial",
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
    ]
